name: ${PROJECT}

services:
  server:
    image: ${PROJECT}-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8001"
    mem_limit: 4g

  client:
    image: ${PROJECT}-client
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./data:/data:ro
    mem_limit: 4g
