services:
  server:
    image: ${PROJECT}-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8001:8001"

  client:
    image: ${PROJECT}-client
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./data:/data:ro
    depends_on:
      - server
    stdin_open: true
    tty: true
